### ISSUE TITLE
[SETUP] Please help with my setup

### ISSUE THREAD

**Issue by felisida** [h4de5/home-assistant-vimar#22]
hi Andy
yesterday I re-installed HA core directly on a debian Linux machine (it was previously supervised on proxmox), I restarted from scratch, but when I start it gives me this error: Certificate download error: VimarApiError: Saving certificate failed: [Errno 2] No such file or directory: 'https: //xxx.xxx.xxx.xxxx: 443 / vimarbyweb / modules / vimar-byme / script / rootCA.VIMAR.crt'
if I manually go to the link, the file downloads it, I cmq I had put it in the folder ./homeassistant where there is the configuration file

my configuration is:
vimar_platform:
   username: xxxx
   password: xxx
   host: 192.168.1.110
   scheme: https
   port: 443
   certificate: rootCA.VIMAR.crt

**Comment by felisida** [comment]
the complete log
2021-01-03 12:52:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-03 12:52:53 ERROR (MainThread) [custom_components.vimar_platform] Certificate download error: VimarApiError: Saving certificate failed: [Errno 2] No such file or directory: 'https://192.168.86.110:443/vimarbyweb/modules/vimar-byme/script/rootCA.VIMAR.crt'
2021-01-03 12:52:53 ERROR (MainThread) [homeassistant.setup] Error during setup of component vimar_platform
Traceback (most recent call last):
File "/home/felice/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/home/felice/.homeassistant/custom_components/vimar_platform/__init__.py", line 91, in async_setup
vimarproject, vimarconnection = await _validate_vimar_credentials(hass, vimarconfig)
File "/home/felice/.homeassistant/custom_components/vimar_platform/__init__.py", line 205, in _validate_vimar_credentials
raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady

**Comment by felisida** [comment]
I'm sorry I found the issue!  I have to put the .crt file  in home assistant folder and not .homassistant
