### ISSUE TITLE
[SETUP]

### ISSUE THREAD

**Issue by lollo03** [h4de5/home-assistant-vimar#4]
The error:
```
2020-06-08 13:03:11 INFO (MainThread) [custom_components.vimar_platform.vimarlink] Vimar link initialized

2020-06-08 13:03:11 ERROR (SyncWorker_16) [custom_components.vimar_platform.vimarlink] Other error occurred: SSLError(MaxRetryError('HTTPSConnectionPool(host=\'192.168.1.110\', port=443): Max retries exceeded with url: /vimarbyweb/modules/system/user_login.php?sessionid=&username=ha&password=ha&remember=0&op=login (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))

2020-06-08 13:03:13 ERROR (MainThread) [custom_components.vimar_platform] Could not connect to Vimar Webserver 192.168.1.110
```

How can I force an HTTP connection at my webserver? Or, alternatively, how can I fix my SSL certificate?

My config:
```
vimar_platform:
  username: ha
  password: ******
  host: 192.168.1.110
  schema: http
  port: 80

```

**Setup**
 - raspberryPI
 - Home-Assistant Version: v0.110.4

Thank you for your help. I very much appreciate this project.

**Comment by h4de5** [comment]
Hello. i just tried out http connection and it seems this option can be removed - the webserver is always forwarding to https.

try this config:

```
vimar_platform:
  username: ha
  password: ******
  host: 192.168.1.110
  schema: https
  port: 443
```

**Comment by lollo03** [comment]
I tried, still won't work.

```
2020-06-08 14:42:00 INFO (MainThread) [custom_components.vimar_platform.vimarlink] Vimar link initialized
2020-06-08 14:42:00 ERROR (SyncWorker_4) [custom_components.vimar_platform.vimarlink] Other error occurred: SSLError(MaxRetryError('HTTPSConnectionPool(host=\'192.168.1.110\', port=443): Max retries exceeded with url: /vimarbyweb/modules/system/user_login.php?sessionid=&username=ha&password=ha&remember=0&op=login (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))
2020-06-08 14:42:02 ERROR (MainThread) [custom_components.vimar_platform] Could not connect to Vimar Webserver 192.168.1.110
2020-06-08 14:42:02 ERROR (MainThread) [homeassistant.setup] Error during setup of component vimar_platform
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/vimar_platform/__init__.py", line 110, in async_setup
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady
```

This is my webserver configuration...
![image](https://user-images.githubusercontent.com/23106263/84031792-9a788680-a996-11ea-9479-20dfda62d325.png)
Is okay?

**Comment by h4de5** [comment]
see my answer over there: https://github.com/h4de5/VimarWebserverApi/issues/1#issuecomment-640590554

it seems there is a problem during downloading the certificate it self .

**Comment by lollo03** [comment]
It still won't work. Maybe a web server update will help (I'm on currently v1.13.0 )?

**Comment by h4de5** [comment]
oh. I see - i though I already asked about that.
I only tested it so far with the latest one - v1.25.

**Comment by lollo03** [comment]
Ok, I tried I only have to figure out how to obtain the XML file. Do you have any advice?

**Comment by alfienero** [comment]
Ciao Lollo, to get your XML file you need to load the plant configuration file (.db) on EasyToolProfessional and to export XML from there

**Comment by lollo03** [comment]
Unfortunately, I have only the webserver DB... and I don't have any equipment to connect to my central.

**Comment by alfienero** [comment]
You should ask the installer to provide you the file, Have you solved the config/certificate issue? Is the vimar_platform starting?

**Comment by lollo03** [comment]
I made the database backup but he wants the XML file. I tried to restore de database but it didn't work. I call the installer and let him send me the file.

**Comment by h4de5** [comment]
I am not sure - but I think you can export the xml file directly from EasyToolProfessional - https://www.vimar.com/de/int/easytool-professional-11527162.html
first load the db there and then export it as xml.
havn't done this since I did the initial setup.

**Comment by alfienero** [comment]
Yes Andi I confirm you that you can export xml from EasyTool, I did it because xml is needed for the Ilevia software installation.

**Comment by lollo03** [comment]
> I am not sure - but I think you can export the xml file directly from EasyToolProfessional - https://www.vimar.com/de/int/easytool-professional-11527162.html
> first load the db there and then export it as xml.
> havn't done this since I did the initial setup.

I have only the web-server database :( I can still do it?

**Comment by alfienero** [comment]
if you are unable to get .db from the installer, you can buy the vimar interface to connect pc to by me module, maybe is unexpensive now that the new webserver is out

**Comment by lollo03** [comment]
I will try, thank you for your help and congrats for this awesome project. I would like to help with the development.

**Comment by h4de5** [comment]
Thanks for the support. I really hope you get the webserver working up and running again :/

**Comment by alfienero** [comment]
I don't know if I got your problem (just webserver software update, right?) However as far as I can remember I've always updated webserver firmware using downloaded firmware files (vimar site) and never asked me for reloading xml or maybe some alert prompted, but in the end I never used xml files: the webserver itself took again the file that already has without any action
