### ISSUE TITLE
[FEATURE] New device Energy guard

### ISSUE THREAD

**Issue by alfienero** [h4de5/home-assistant-vimar#6]
Hi Andi, I have an energy guard device that measures the electricty consumption in my home. I would be interested only in a sensor that updates my instant consumption to create an automation that alerts me when I'm above a certain limit

The row is Row000005: '321','consumo_totale','-1','0.310' (the device is set to consider also your potential production - zero in my case - with row n.6 and the net demand row n.8

![Cattura](https://user-images.githubusercontent.com/43268946/85266289-f56cac00-b473-11ea-94a1-55fa3b873340.JPG)

```
Response: DBMG-000
NextRows: 107
Row000001: 'ID','NAME','STATUS_ID','CURRENT_VALUE'
Row000002: '198','_DPAD_DBCONSTANT_VIMAR_BYME_TRIGGEROBJECT_SAI_LOG_ALARM','-1','0'
Row000003: '229','_DPAD_DBCONSTANT_VIMAR_BYME_TRIGGEROBJECT_VIDEOMESSAGE_UNHANDLED','-1','0'
Row000004: '319','scambio_totale','-1','0.310'
Row000005: '321','consumo_totale','-1','0.310'
Row000006: '323','produzione_totale','-1','0'
Row000007: '325','immissione_totale','-1','-0.000'
Row000008: '327','prelievo_totale','-1','0.310'
Row000009: '329','autoconsumo_totale','-1','0.000'
```

**Comment by felisida** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:xmethods-dpadws">
    <SOAP-ENV:Body SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <ns:service-databasesocketoperationResponse>
            <result-len>Response payload length: 721</result-len>
            <result>DPCM-0000</result>
            <payload-len>721</payload-len>
            <payload>Response: DBMG-000&#xA;NextRows: 11&#xA;Row000001: 'ID','NAME','STATUS_ID','CURRENT_VALUE'&#xA;Row000002: '229','_DPAD_DBCONSTANT_VIMAR_BYME_TRIGGEROBJECT_VIDEOMESSAGE_UNHANDLED','-1','0'&#xA;Row000003: '265','_DPAD_DBCONSTANT_VIMAR_BYME_TRIGGEROBJECT_SENSORS_HUMIDITY_ALARM','-1','0'&#xA;Row000004: '270','_DPAD_DBCONSTANT_VIMAR_BYME_TRIGGEROBJECT_SAI2_LOG_ALARM','-1','0'&#xA;Row000005: '286','scambio_totale','-1','-2.950'&#xA;Row000006: '288','consumo_totale','-1','0.480'&#xA;Row000007: '290','produzione_totale','-1','3.430'&#xA;Row000008: '292','immissione_totale','-1','2.950'&#xA;Row000009: '294','prelievo_totale','-1','0.000'&#xA;Row000010: '296','autoconsumo_totale','-1','0.480'&#xA;Row000011: '8548','_DPAD_PRODUCT_VIMARBYME_CERTIFICATE_TRIGGER','-1','0'&#xA;</payload>
        </ns:service-databasesocketoperationResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by h4de5** [comment]
@alfienero @felisida I uploaded a first version - but I cannot test it. please have a look. let me know if it breaks stuff - than I will move it to a feature branch.

**Comment by felisida** [comment]
good mornign I tried your upgrade there isn't breaks, but I have not found new entities...

**Comment by alfienero** [comment]
Unfortunately same for me, below the log

```
2020-06-26 09:18:41 INFO (SyncWorker_6) [custom_components.vimar_platform.vimarlink] Vimar login ok
2020-06-26 09:18:41 INFO (SyncWorker_8) [custom_components.vimar_platform.vimarlink] get_main_groups start
2020-06-26 09:18:41 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.updater
2020-06-26 09:18:41 INFO (SyncWorker_8) [custom_components.vimar_platform.vimarlink] get_main_groups ends - found 8 groups
2020-06-26 09:18:41 INFO (SyncWorker_8) [custom_components.vimar_platform.vimarlink] get_devices started
2020-06-26 09:18:41 INFO (SyncWorker_8) [custom_components.vimar_platform.vimarlink] get_devices ends - found 36 devices
2020-06-26 09:18:41 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavatrice
2020-06-26 09:18:41 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Forno
2020-06-26 09:18:41 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavastoviglie
2020-06-26 09:18:41 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Piano cottura
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light started!
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light complete!
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch started!
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Buonanotte
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Uscita
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Cinema
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Ingresso
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch complete!
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate started!
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate complete!
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover started!
2020-06-26 09:18:41 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover complete!
```

**Comment by h4de5** [comment]
this could be for the same reason, for we are not seeing all scenes: the energy guard may not be bound to a room. 
I have to change the way how the initial query collects all entities.

**Comment by alfienero** [comment]
Just to add more information: on my side, I have all the scenarios working including the 4 ones mentioned with uncommon naming schema. Maybe I got all devices/scenarios because I don't have many as Felice (felisida), mine is a small apartment.

**Comment by h4de5** [comment]
This should now be working as well. energie produced and consumed should be available as a sensor now.
Let me know if there is still something missing - i'll just reopen the issue then.

**Comment by felisida** [comment]
unfortunately on my side I don't see the two sensor for energie produced and consumed 
2020-06-29 11:00:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 11:00:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for vimar_platform which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 11:00:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 11:00:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 11:01:00 INFO (MainThread) [custom_components.vimar_platform.vimarlink] Vimar link initialized
2020-06-29 11:01:00 INFO (MainThread) [custom_components.vimar_platform] Vimar CA Certificate is already in place: rootCA.VIMAR.crt
2020-06-29 11:01:04 INFO (SyncWorker_2) [custom_components.vimar_platform.vimarlink] Vimar login ok
2020-06-29 11:01:04 INFO (SyncWorker_4) [custom_components.vimar_platform.vimarlink] get_main_groups start
2020-06-29 11:01:05 INFO (SyncWorker_4) [custom_components.vimar_platform.vimarlink] get_main_groups ends - found 12 groups
2020-06-29 11:01:05 INFO (SyncWorker_6) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-06-29 11:01:05 INFO (SyncWorker_6) [custom_components.vimar_platform.vimarlink] load sql ends - found 50 devices
2020-06-29 11:01:05 INFO (SyncWorker_2) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-06-29 11:01:05 INFO (SyncWorker_2) [custom_components.vimar_platform.vimarlink] load sql ends - found 70 devices
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Cucina
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Soggiorno
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Camera matrimoniale
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Camera ospiti
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Cameretta
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Bagno ospiti
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Bagno Camera
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Studio
2020-06-29 11:01:05 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Asciugatrice
2020-06-29 11:01:05 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Forno
2020-06-29 11:01:05 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavastoviglie
2020-06-29 11:01:05 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavatrice
2020-06-29 11:01:05 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Microonde
2020-06-29 11:01:05 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Piano induzione
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch started!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch complete!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.sensor] Vimar Sensor started!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.sensor] Vimar Sensor complete!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate started!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate complete!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover started!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover complete!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light started!
2020-06-29 11:01:05 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light complete!

**Comment by h4de5** [comment]
oh. i thought you meant https://github.com/h4de5/home-assistant-vimar/issues/9#issuecomment-650941330 it was working already. 

there should only be one sensor and the details of produced and consumed should be sent as states. do you see at least one sensor on top of the lovelace interface?

**Comment by felisida** [comment]
hi, i searched other time on my entities, but i have only 3 sensor that are the energy guards, am i making some mistake?
![Schermata 2020-06-29 alle 15 15 46](https://user-images.githubusercontent.com/51525150/86010494-c7f7a380-ba1b-11ea-92a0-7d4258ba4d9b.jpg)

**Comment by h4de5** [comment]
i just fixed something in the sensors - maybe that was missing.
but each of those devices should deliver a value in kilowatts - and have all the other measurements available as attributes. (again I can't tell you where to search for them, as I don't know how the result looks like - just seeing it here from the development perspective)

**Comment by felisida** [comment]
no result,

2020-06-29 19:40:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 19:40:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 19:40:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 19:40:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for vimar_platform which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-29 19:40:15 INFO (MainThread) [custom_components.vimar_platform.vimarlink] Vimar link initialized
2020-06-29 19:40:15 INFO (MainThread) [custom_components.vimar_platform] Vimar CA Certificate is already in place: rootCA.VIMAR.crt
2020-06-29 19:40:16 WARNING (zeroconf-ServiceBrowser__axis-video._tcp.local.-_printer._tcp.local.-_dkapi._tcp.local.-_api._udp.local.-_miio._udp.local.-_elg._tcp.local.-_ipp._tcp.local.-_esphomelib._tcp.local.-_viziocast._tcp.local.-_spotify-connect._tcp.local.-_wled._tcp.local.-_daap._tcp.local.-_googlecast._tcp.local.-_ipps._tcp.local.-_hap._tcp.local._217090) [zeroconf] Error sending through socket 17
Traceback (most recent call last):
  File "/Users/felice/.homeassistant/deps/lib/python/site-packages/zeroconf/__init__.py", line 2792, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 55] No buffer space available
2020-06-29 19:40:17 INFO (SyncWorker_0) [custom_components.vimar_platform.vimarlink] Vimar login ok
2020-06-29 19:40:17 INFO (SyncWorker_3) [custom_components.vimar_platform.vimarlink] get_main_groups start
2020-06-29 19:40:18 INFO (SyncWorker_3) [custom_components.vimar_platform.vimarlink] get_main_groups ends - found 12 groups
2020-06-29 19:40:18 INFO (SyncWorker_7) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-06-29 19:40:18 INFO (SyncWorker_7) [custom_components.vimar_platform.vimarlink] load sql ends - found 50 devices
2020-06-29 19:40:18 INFO (SyncWorker_6) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-06-29 19:40:18 INFO (SyncWorker_6) [custom_components.vimar_platform.vimarlink] load sql ends - found 70 devices
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Cucina
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Soggiorno
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Camera matrimoniale
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Camera ospiti
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Cameretta
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Bagno ospiti
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Bagno Camera
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform] Unsupported object returned from web server: CH_Audio / Studio
2020-06-29 19:40:18 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Asciugatrice
2020-06-29 19:40:18 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Forno
2020-06-29 19:40:18 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavastoviglie
2020-06-29 19:40:18 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavatrice
2020-06-29 19:40:18 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Microonde
2020-06-29 19:40:18 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Piano induzione
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch started!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch complete!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.sensor] Vimar Sensor started!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.sensor] Vimar Sensor complete!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate started!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate complete!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover started!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover complete!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light started!
2020-06-29 19:40:18 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light complete!
2020-06-29 19:40:18 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up vimar_platform platform for sensor
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 443, in _async_add_entity
    entity.async_write_ha_state()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/Users/felice/.homeassistant/custom_components/vimar_platform/sensor.py", line 126, in state
    first_value = next(value_iterator)
StopIteration

The above exception was the direct cause of the following exception:

**Comment by h4de5** [comment]
Hope this big is fixed now.

**Comment by felisida** [comment]
I'm sorry the same result only 3 sensors of energy guards

**Comment by h4de5** [comment]
if you have 3 energie guards, then there will only be 3 sensors in home-assistant.
I tried to create a separate sensor for each value, but this would result in way more updates. 
each of your three sensors should have all the values listed as attributes - you should be able to open them like this:

![image](https://user-images.githubusercontent.com/6115324/86100111-b2848700-bab8-11ea-928e-453a744f1a73.png)

**Comment by alfienero** [comment]
Hi Andi, I'm back home for a week. I've just updated the vimar component, but I don't get any new entities, I don't have sensors in the vimar component

```
2020-07-05 12:27:34 INFO (SyncWorker_0) [custom_components.vimar_platform.vimarlink] Vimar login ok
2020-07-05 12:27:35 INFO (SyncWorker_0) [custom_components.vimar_platform.vimarlink] get_main_groups start
2020-07-05 12:27:35 INFO (SyncWorker_0) [custom_components.vimar_platform.vimarlink] get_main_groups ends - found 8 groups
2020-07-05 12:27:35 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-07-05 12:27:36 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.updater
2020-07-05 12:27:36 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] load sql ends - found 36 devices
2020-07-05 12:27:36 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-07-05 12:27:37 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] load sql ends - found 38 devices
2020-07-05 12:27:37 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavatrice
2020-07-05 12:27:37 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Forno
2020-07-05 12:27:37 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavastoviglie
2020-07-05 12:27:37 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Piano cottura
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light started!
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light complete!
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch started!
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch complete!
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover started!
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover complete!
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate started!
2020-07-05 12:27:37 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate complete!
```

**Comment by felisida** [comment]
hi Andi, last week I was sick, any news about your job?

**Comment by h4de5** [comment]
not yet. had lots to do myself - still working on the separated sensors for this energy guard. 

@alfienero the device CH_Carichi_3F is the touch panel, right? I am not sure why it does not find any sensors - you can try to increase the logging level on the vimar_platform to debug - maybe it gives us more hints.

**Comment by alfienero** [comment]
> not yet. had lots to do myself - still working on the separated sensors for this energy guard.
> 
> @alfienero the device CH_Carichi_3F is the touch panel, right? I am not sure why it does not find any sensors - you can try to increase the logging level on the vimar_platform to debug - maybe it gives us more hints.

Hi Andi sorry for the late reply. These 4 devices:
CH_Carichi_3F / Lavatrice
CH_Carichi_3F / Forno
CH_Carichi_3F / Lavastoviglie
CH_Carichi_3F / Piano cottura

are 4 electrical load controls. If my home is consuming above the electricity distributor limit (set at 4.5 KW/h for me) the by me bus disconnect 4 energy demanding devices: washing machine, oven, dishwasher and electrical stove. For me is not relevant that those devices would be recognized by HA.

How can I increase the logging level to find out why the energy measure sensor is missing?

**Comment by h4de5** [comment]
ah I see. I will add those in the next release. 
unfortunatelly I started to work on several things at the same time, so I do not have a working setup ready right now. I'll update you as soon as I have something to test again.

to change the logging level:

```yaml
logger:
  default: warning
  logs:
    custom_components.vimar_platform: debug
```

**Comment by alfienero** [comment]
I did a debug log but the info are pretty similar for me, but maybe it can be useful for you
```
2020-07-13 16:21:38 INFO (MainThread) [custom_components.vimar_platform.vimarlink] Vimar link initialized
2020-07-13 16:21:38 DEBUG (SyncWorker_9) [custom_components.vimar_platform.vimarlink] Request ignores ssl certificate
2020-07-13 16:21:43 INFO (SyncWorker_9) [custom_components.vimar_platform.vimarlink] Vimar login ok
2020-07-13 16:21:43 DEBUG (SyncWorker_9) [custom_components.vimar_platform.vimarlink] Got a new Vimar Session id: 5f0c6df7efa96
2020-07-13 16:21:43 INFO (SyncWorker_6) [custom_components.vimar_platform.vimarlink] get_main_groups start
2020-07-13 16:21:43 DEBUG (SyncWorker_6) [custom_components.vimar_platform.vimarlink] Request ignores ssl certificate
2020-07-13 16:21:43 INFO (SyncWorker_6) [custom_components.vimar_platform.vimarlink] get_main_groups ends - found 8 groups
2020-07-13 16:21:43 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-07-13 16:21:43 DEBUG (SyncWorker_1) [custom_components.vimar_platform.vimarlink] Request ignores ssl certificate
2020-07-13 16:21:44 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] load sql ends - found 36 devices
2020-07-13 16:21:44 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] get_scenes started
2020-07-13 16:21:44 DEBUG (SyncWorker_1) [custom_components.vimar_platform.vimarlink] Request ignores ssl certificate
2020-07-13 16:21:45 INFO (SyncWorker_1) [custom_components.vimar_platform.vimarlink] load sql ends - found 38 devices
2020-07-13 16:21:45 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavatrice
2020-07-13 16:21:45 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Forno
2020-07-13 16:21:45 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Lavastoviglie
2020-07-13 16:21:45 WARNING (MainThread) [custom_components.vimar_platform] Unknown object returned from web server: CH_Carichi_3F / Piano cottura
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light started!
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.light] Vimar Light complete!
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch started!
2020-07-13 16:21:45 DEBUG (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Buonanotte
2020-07-13 16:21:45 DEBUG (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Uscita
2020-07-13 16:21:45 DEBUG (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Cinema
2020-07-13 16:21:45 DEBUG (MainThread) [custom_components.vimar_platform] Found a device with an uncommon naming schema: Ingresso
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.switch] Vimar Switch complete!
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover started!
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.cover] Vimar Cover complete!
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate started!
2020-07-13 16:21:45 INFO (MainThread) [custom_components.vimar_platform.climate] Vimar Climate complete!
2020-07-13 16:21:45 DEBUG (SyncWorker_5) [custom_components.vimar_platform.vimarlink] Request ignores ssl certificate
2020-07-13 16:21:45 DEBUG (SyncWorker_8) [custom_components.vimar_platform.vimarlink] Request ignores ssl certificate
```

**Comment by h4de5** [comment]
yes. I though those are wall panels, therefore I skipped them from actually reading any data from it.

**Comment by h4de5** [comment]
with the latest update - each sensor should be listed separately in ha.

**Comment by alfienero** [comment]
Hi Andi I just tried the new version and lot of sensors appeared including the one that I need (the energy consumed in the whole house). Thank you again!!!

**Comment by h4de5** [comment]
I am closing this issue as it seems to be working already. Please let me know if that's not the case.
